import express from 'express'; import cors from 'cors'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { createDb, history, now } from './db.js'; import { validateClaim, deterministicChecks } from './validation.js'; import { findPolicy, POLICIES } from './policies.js'; import { classifyClaim } from './ai.js'; import { logger } from './logger.js';
export function makeApp(db = createDb()) {
  const app = express(); app.use(cors()); app.use(express.json());
  const serverDirectory = path.dirname(fileURLToPath(import.meta.url));
  const detail = id => { const claim = db.prepare('SELECT * FROM claims WHERE id=?').get(id); if (!claim) return null; claim.receiptAvailable = Boolean(claim.receipt_available); claim.review = db.prepare('SELECT * FROM reviews WHERE claim_id=?').get(id); if (claim.review) { claim.review.uncertain = Boolean(claim.review.uncertain); for (const key of ['missing_information','deterministic_results']) claim.review[key] = JSON.parse(claim.review[key]); claim.review.policyEvidence = db.prepare('SELECT * FROM policies WHERE id=?').get(claim.review.policy_id); } claim.history = db.prepare('SELECT * FROM decision_history WHERE claim_id=? ORDER BY id').all(id); return claim; };
  app.get('/api/policies', (req,res)=>res.json(POLICIES)); app.get('/api/policies/:category', (req,res)=>{ const p=findPolicy(req.params.category); p ? res.json(p) : res.status(404).json({error:'Policy not found'}); });
  app.get('/api/claims', (req,res)=>{ const claims=db.prepare('SELECT * FROM claims ORDER BY id DESC').all().map(c=>({...c,receiptAvailable:Boolean(c.receipt_available)})); const totals={ submitted:claims.length, approved:0, pending:0, rejected:0, clarification:0, totalAmount:claims.reduce((s,c)=>s+c.amount,0) }; claims.forEach(c=>{if(c.status==='APPROVED')totals.approved++; else if(c.status==='REJECTED')totals.rejected++; else if(c.status==='REQUIRES_CLARIFICATION')totals.clarification++; else totals.pending++;}); res.json({claims,totals}); });
  app.post('/api/claims', async (req,res,next)=>{ try { const input=req.body; const errors=validateClaim(input); if(errors.length) { logger.warn('claim.validation.failed', { fields: errors }); return res.status(400).json({error:'Validation failed',details:errors}); } const duplicates=db.prepare('SELECT id FROM claims WHERE claimant=? AND date=? AND amount=? AND currency=? AND category=?').all(input.claimant,input.date,Number(input.amount),input.currency.toUpperCase(),input.category); const created=now(); const result=db.prepare('INSERT INTO claims (claimant,date,category,amount,currency,description,receipt_available,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(input.claimant,input.date,input.category,Number(input.amount),input.currency.toUpperCase(),input.description,Number(Boolean(input.receiptAvailable)),created,created); const claim={...input,id:result.lastInsertRowid,amount:Number(input.amount),currency:input.currency.toUpperCase()}; history(db,claim.id,'CLAIM_SUBMITTED',null,'PENDING_REVIEW',null,input.claimant); const checks=deterministicChecks(claim,duplicates); const ai=await classifyClaim(claim); const policy=findPolicy(ai.classification); const status=ai.provider==='unavailable' || checks.length || ai.uncertain ? 'REQUIRES_REVIEW' : ai.missingInformation.length ? 'REQUIRES_CLARIFICATION' : 'COMPLIANT'; db.prepare('INSERT INTO reviews (claim_id,classification,confidence,uncertain,status,explanation,missing_information,deterministic_results,policy_id,provider,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(claim.id,ai.classification,ai.confidence,Number(ai.uncertain),status,ai.explanation,JSON.stringify(ai.missingInformation),JSON.stringify(checks),policy?.id||null,ai.provider,now()); history(db,claim.id,'AI_REVIEW_COMPLETED','PENDING_REVIEW','PENDING_REVIEW',`Review status: ${status}`,'System'); logger.info('claim.created', { claimId: claim.id, category: claim.category, reviewStatus: status, findingCount: checks.length, aiProvider: ai.provider }); res.status(201).json(detail(claim.id)); } catch(e){next(e)} });
  app.get('/api/claims/:id', (req,res)=>{const c=detail(req.params.id); c?res.json(c):res.status(404).json({error:'Claim not found'});}); app.get('/api/claims/:id/history',(req,res)=>{const c=detail(req.params.id);c?res.json(c.history):res.status(404).json({error:'Claim not found'});});
  app.post('/api/claims/:id/decision',(req,res)=>{const claim=detail(req.params.id); if(!claim)return res.status(404).json({error:'Claim not found'}); const {action,reason,actor='Reviewer'}=req.body; const map={APPROVE:'APPROVED',REJECT:'REJECTED',REQUEST_CLARIFICATION:'REQUIRES_CLARIFICATION'}; if(!map[action])return res.status(400).json({error:'Invalid reviewer action'}); if((action==='REJECT'||action==='REQUEST_CLARIFICATION')&&!String(reason||'').trim())return res.status(400).json({error:'A reason is required'}); db.prepare('UPDATE claims SET status=?,updated_at=? WHERE id=?').run(map[action],now(),claim.id); history(db,claim.id,action,claim.status,map[action],reason,actor); logger.info('claim.decision.recorded', { claimId: claim.id, action, previousStatus: claim.status, newStatus: map[action], actor });res.json(detail(claim.id));});
  app.post('/api/claims/:id/override',(req,res)=>{const claim=detail(req.params.id);if(!claim)return res.status(404).json({error:'Claim not found'});const {classification,reason,actor='Reviewer'}=req.body;if(!findPolicy(classification))return res.status(400).json({error:'Classification must match a policy'});if(!String(reason||'').trim())return res.status(400).json({error:'Override reason is required'});db.prepare('UPDATE reviews SET classification=?,policy_id=?,uncertain=0 WHERE claim_id=?').run(classification,findPolicy(classification).id,claim.id);history(db,claim.id,'CLASSIFICATION_OVERRIDDEN',claim.review?.classification,classification,reason,actor);res.json(detail(claim.id));});
  app.use((err,req,res,_next)=>{logger.error('api.request.failed',{ method:req.method, path:req.path, message:err.message });res.status(500).json({error:'Unexpected server error'});});
  const clientBuild = path.resolve(serverDirectory, '../dist');
  app.use(express.static(clientBuild));
  app.get('*', (req, res) => res.sendFile(path.join(clientBuild, 'index.html')));
  return app;
}
